version: '3'
services:
  core:
    build: core
    environment:
        DATABASE_URL: "postgresql://sql/danbooru2"
        SECRET_TOKEN: 
        SESSION_SECRET_KEY:
        DANBOORU_ELASTICSEARCH_HOST: es
        DANBOORU_SSL_OPTIONS: "{}"
        DANBOORU_MEMCACHED_SERVERS: memcached:11211
        DANBOORU_REDIS_URL: "redis://redis:6379"
        REDIS_URL: "redis://redis:6379"
        WAIT_HOSTS: sql:5432, es:9200, memcached:11211, redis:6379
        WAIT_HOSTS_TIMEOUT: 180
    depends_on:
        - sql
        - es
        - redis
        - memcached
    volumes:
      - "./core/danbooru_local_config.rb:/app/config/danbooru_local_config.rb"
      - "${MOUNT_LOG}:/app/log"
      - "${MOUNT_DATA}:/app/public/data"
      - "${MOUNT_ASSETS}:/app/public/assets"
      - static_files:/app/public
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
        ES_JAVA_OPTS: -Xms512m -Xmx512m
        discovery.type: single-node
    volumes:
      - "${MOUNT_ES}:/usr/share/elasticsearch/data"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  sql:
    build: sql
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changethis
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: public
    volumes:
      - "${MOUNT_SQL}:/var/lib/postgresql/data"
  redis:
     image: redis:6-alpine
  memcached:
     image: memcached:1-alpine

  frontend:
    build: frontend
    depends_on:
        - core
    environment:
      - NGINX_PORT
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    command: /bin/bash -c "envsubst '$${NGINX_PORT}' < /etc/nginx/conf.d/e621.nginx.conf.templ > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    volumes:
      - "${NGINX_LOGS_MOUNT}:/var/log/nginx"
      - "${MOUNT_DATA}:/var/www/danbooru/current/public/data"
      - "${MOUNT_ASSETS}:/var/www/danbooru/current/public/assets"
      - static_files:/var/www/danbooru/current/public

volumes:
  static_files:
