apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: sql
  name: sql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sql
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: sql
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: public
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_PASSWORD
          value: changethis
        - name: POSTGRES_USER
          value: root
        image: noirscape/e621:sql
        imagePullPolicy: ""
        name: sql
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
